import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Play it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-cyan-300">
      Hello Guys!
    </h1>
    </div>
  )
}
